### ISSUE TITLE
Support different databases

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeeqs#12]
* document how to use a different database (e.g. Postgres, MySQL, etc.) to store the aggregated data in

**Comment by asaf** [comment]
I see that Spring supports [Mongo](https://docs.spring.io/spring-data/mongodb/docs/1.2.0.RELEASE/reference/html/mongo.repositories.html) too, it will be great to have support for non RDBMS too.

**Comment by saig0** [comment]
Since the application uses Spring-JPA to access the internal database, it should be possible to use MongoDB as well. But I'm currently not sure that is the best way to support different databases with Spring Boot / Docker. The problem is that the specific database driver must be in the classpath.

Any idea?

**Comment by asaf** [comment]
I'm not sure how well JPA works with Mongo, it's more suited for RDBMS but Spring supports it,

regarding database driver in classpath, you can't embed all drivers in your docker,
if someone needs a special driver, he can inherit fro your docker and add it to its own.

**Comment by saig0** [comment]
I documented how to change the database here: https://github.com/zeebe-io/zeeqs#configuration

**Comment by asaf** [comment]
nice!
