### ISSUE TITLE
JobRecord - record.Metadata.Key is set to -1 when intent is CREATE

### ISSUE THREAD

**Issue by asaf** [zeebe-io/zeeqs#18]
Hey,

I think that when JobRecord intent is _CREATE_ the value of _record.Metadata.Key_ is set to -1 (at least that's the case with broker 0.22.2, not sure if it's a bug or as expected)

I think that this will cause JPA to create a record with -1 as ID.

Maybe you should filter jobs when key = -1,

note: this is true for other entities such incidents & messages

Thanks,

Asaf.

**Comment by saig0** [comment]
Good point. Thank you for reporting :+1:

**Comment by saig0** [comment]
Fixed by #21
