### ISSUE TITLE
Suggestion: add Time.creationTime

### ISSUE THREAD

**Issue by asaf** [zeebe-io/zeeqs#19]
Hey,

Since timers are overridden, it's currently impossible to know the amount of time took for a timer to complete its work,

Adding _timer. creationTime_  in [createTimer](https://github.com/zeebe-io/zeeqs/blob/master/hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt#L351) can help.

**Comment by saig0** [comment]
Good idea :+1:
