### ISSUE TITLE
Data persistence issue

### ISSUE THREAD

**Issue by asiri-kusal** [zeebe-io/zeeqs#20]
Hi,

Zeeqs can query current insert data only, When i'm restart zeeqs service it can't query exist(old active) data in cluster. But will create new instance and query using zeeqs, it ability  to query and show it.
Therefore 
-  Zeeqs have to connect with elasticsearch server or zeebe cluster and it ability get old active data of cluster

**Comment by saig0** [comment]
Hi @asiri-kusal,

by default, ZeeQS use an in-memory H2 database. If you want the data to be persistent (e.g. after a restart) then you need to use a persistent database. 

The simplest way could be to use a file-based H2. That should be possible by 
* changing the config `spring.datasource.url` to `spring.datasource.url=jdbc:h2:mem:zeeqs;DB_CLOSE_DELAY=-1`, e.g., via environment variable
* or, declare the database in the docker-compose file 

Does this help you?

Related to #12

**Comment by saig0** [comment]
I documented how to change the database here: https://github.com/zeebe-io/zeeqs#configuration
