### ISSUE TITLE
Suggestion chang enums to @Enumerated(EnumType.STRING)

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/zeeqs#64]
Using `@Enumerated(EnumType.STRING)` on enum fields leads to more meaningful data in the database.  

It is much easier to debug something in the database when you can read "ACTIVATED" instead of 0

Would you consider changing to strings ?

I could implement a PR that does the change, and provides a SQL script to migrate the schema and data.

**Comment by saig0** [comment]
@cameronbraid thanks for reporting :+1: 

I assumed that this would be the default behavior :see_no_evil: 
So, yes it makes sense to change it.

Feel free to open a PR :tada: 
I think a SQL migration script is not necessary.

**Comment by cameronbraid** [comment]
What about changing to using @ManyToOne for relationships instead of just using long keys

for example

Variable.kt - ```workflowInstanceKey```
```

@Entity
class Variable(
        @Id val key: Long,
        val name: String,
        val workflowInstanceKey: Long,
        val scopeKey: Long,
        var value: String,
        var timestamp: Long
)
```

change to  ```workflowInstance```

```

@Entity
class Variable(
        @Id val key: Long,
        val name: String,

        @ManyToOne(fetch=FetchType.LAZY)
        @JoinColumn(name="workflowInstanceKey")
        val workflowInstance: WorkflowInstance,

        val scopeKey: Long,
        var value: String,
        var timestamp: Long
)
```

This way using jpa I can create a query in my repo like the folloiwing to find a workflow instance for a variable with a value

```
  @Query("select distinct v.workflowInstance from Variable v where v.name = :name and v.value = :value and v.workflowInstance.bpmnProcessId = :bpmnProcessId")
  public List<WorkflowInstance> findForVariableNameAndJsonValueAndBpmnProcessId(@Param("name") String name, @Param("value") String jsonValue, @Param("bpmnProcessId") String bpmnProcessId); 
```

**Comment by saig0** [comment]
@cameronbraid thank you for the suggestion. 

For now, I don't want to introduce strict relationships between the entities by using `@ManyToOne`. My reasons are that
* I don't want to bind the storage to a relational database 
* I want to keep it simple
* the records may be imported in a different order (e.g. a variable record before the related workflow instance record)

**Comment by cameronbraid** [comment]
No worries.. I worked out that I can join in a jpa query anyway, so I can still do 

```
@Query("select distinct wi from Variable v join WorkflowInstance wi on v.workflowInstanceKey = wi.key where v.name = :name and v.value = :value and wi.bpmnProcessId = :bpmnProcessId")
```

And get entities back

**Comment by cameronbraid** [comment]
https://github.com/zeebe-io/zeeqs/issues/64

* Change all enum fields on entities to be @Enumerated(EnumType.STRING)
* add @lob to Incident.errorMessage

**Comment by saig0** [comment]
Done by #67 :tada:
